config/routes.rb
Rails.application.routes.draw do
  resources :api_keys
  authenticated :user do
    root :to => 'redirections#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resource :users, only: [:show] do
    resources :api_keys
  end

  resources :redirections do
    collection do
      get :redirect
    end
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'
    resources :api, :controller => :api, only: [:index, :show]

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :redirections
    end

    match '*path', to: 'api_base#catch_404', via: :all, :format => :json
  end
end

app/models/redirection.rb
class Redirection < ActiveRecord::Base
    require 'csv'

    audited

    validates :from_url, :presence => true, :url => true
    validates :to_url, :presence => true, :url => true
    validates :redirection_type, :presence => true

    validates_uniqueness_of :to_url, :scope => [:from_url, :from_path, :from_query]

    validate :valid_redirection_type

    belongs_to :user

    before_save :strip
    before_save :nilify
    after_save :clear_cache

    REDIRECTION_TYPES = {
        :r300  => {
            :status_code  => 300,
            :description  => 'multiple choices'
        },
        :r301  => {
            :status_code  => 301,
            :description  => 'moved permanently'
        },
        :r302  => {
            :status_code  => 302,
            :description  => 'found'
        },
        :r303  => {
            :status_code  => 303,
            :description  => 'see other'
        },
        :r307  => {
            :status_code  => 307,
            :description  => 'temporary redirect'
        },
        :default  => :r301
    }

    CACHE_TAG = 'redirect_'

    serialize :redirection_type

    def build_url(options = {})
        uri = URI.parse(self.to_url)

        path = redirect_path(options[:to_path])
        query = redirect_query(options[:redirect_to_query])

        if uri.is_a?(URI::HTTPS)
            if Redirection::empty_string_to_nil(query)
                url = URI::HTTPS.build(:host => uri.host, :path => path, :query => "#{query}")
            else
                url = URI::HTTPS.build(:host => uri.host, :path => path)
            end
        elsif uri.is_a?(URI::HTTP)
            if Redirection::empty_string_to_nil(query)
                url = URI::HTTP.build(:host => uri.host, :path => path, :query => "#{query}")
            else
                url = URI::HTTP.build(:host => uri.host, :path => path)
            end
        else
            url = nil
        end

      url.to_s
    end

    def self.find_by_relevance(from_url, from_path = nil, from_query = nil)
      from_path = empty_string_to_nil(from_path).nil? ? 'from_path IS NULL' : "from_path = '#{from_path}'"
      from_query = empty_string_to_nil(from_query).nil? ? 'from_query IS NULL' : "from_query = '#{from_query}'"

      where_statements = Array.new

      where_statements << "from_url = '#{from_url}' AND #{from_path} AND #{from_query}" if from_path && from_query
      where_statements << "from_url = '#{from_url}' AND #{from_path} AND from_query IS NULL" if from_path
      where_statements << "from_url = '#{from_url}' AND from_path IS NULL AND #{from_query}" if from_query
      where_statements << "from_url = '#{from_url}' AND from_path IS NULL AND from_query IS NULL"


      where_statement_string = "(#{where_statements[0]})"
      where_statements.each_with_index do |where_statement, index|
        next if index == 0

        where_statement_string = "#{where_statement_string} OR (#{where_statement})"
      end


      where(where_statement_string)
    end

    def redirection_type_hash
      REDIRECTION_TYPES[self.redirection_type.to_sym]
    end

    def cache_tag(from_path = self.from_path)
      "#{CACHE_TAG}#{self.from_url}_#{from_path}_#{self.from_query}"
    end

    def self.cache_tag(params)
      if AppConfig.get(%w(redirections replace_from_path_empty), APP_CONFIG)
        if (params[:path].is_a?(String) && params[:path].empty?) || params[:path].nil?
          tmp_from_path = AppConfig.get(%w(redirections replace_from_path_empty), APP_CONFIG)
        else
          tmp_from_path = params[:path]
        end
      else
        tmp_from_path = ((params[:path].is_a?(String) && params[:path].empty?) || params[:path].nil?) ? nil : params[:path]
      end

      "#{CACHE_TAG}#{params[:from_url]}_#{tmp_from_path}_#{params[:query]}"
    end

    def write_to_cache(from_path = self.from_path)
      Rails.cache.write(self.cache_tag(from_path), self)
    end

    def self.to_csv(options = {})
      columns = {
          :id                 => 'ID',
          :from_url           => 'From URL',
          :from_path          => 'From Path',
          :from_query         => 'From Query',
          :to_url             => 'To URL',
          :to_path            => 'To Path',
          :redirect_to_query  => 'To Query',
          :redirection_type   => 'Redirection Type',
          :created_at         => 'Created At',
          :updated_at         => 'Updated At'
      }

      CSV.generate(options) do |csv|
        csv << columns.keys.map { |k| columns[k] }
        all.each do |redirection|
          csv << redirection.attributes.values_at(*columns.keys.map { |k| k.to_s })
        end
      end
    end

    private
    def valid_redirection_type

        errors.add(:redirection_type, 'is not valid') unless(self.redirection_type && REDIRECTION_TYPES.has_key?(self.redirection_type.to_sym))
    end

    def strip
      self.from_url             = self.from_url.strip if self.from_url.is_a?(String)
      self.from_path            = self.from_path.strip if self.from_path.is_a?(String)
      self.from_query           = self.from_query.strip if self.from_query.is_a?(String)

      self.to_url               = self.to_url.strip if self.to_url.is_a?(String)
      self.to_path              = self.to_path.strip if self.to_path.is_a?(String)
      self.redirect_to_query    = self.redirect_to_query.strip if self.redirect_to_query.is_a?(String)
    end

    def nilify
      self.from_url           = nil if(self.from_url.is_a?(String) && self.from_url.empty?)
      self.from_path          = AppConfig.get(%w(redirections replace_from_path_empty), APP_CONFIG) if((self.from_path.is_a?(String) && self.from_path.empty?) || self.from_path.nil?)
      self.from_query         = nil if(self.from_query.is_a?(String) && self.from_query.empty?)

      self.to_url             = nil if(self.to_url.is_a?(String) && self.to_url.empty?)
      self.to_path            = AppConfig.get(%w(redirections replace_to_path_empty), APP_CONFIG) if((self.to_path.is_a?(String) && self.to_path.empty?) || self.to_path.nil?)
      self.redirect_to_query  = nil if(self.redirect_to_query.is_a?(String) && self.redirect_to_query.empty?)
    end

    def self.empty_string_to_nil(string)
        if string.is_a?(String) && string.empty?
            nil
        else
            string
        end
    end

  def redirect_path(user_path = nil)
      if self.ignore_user_path?
          # Ignore the passed in user_path
          Redirection::empty_string_to_nil(self.to_path)
      else
        if user_path
            # Passed in user_path is not nil
            Redirection::empty_string_to_nil(user_path)
        else
            # Passed in user_path is nil
            Redirection::empty_string_to_nil(self.to_path)
        end
      end
  end

  def redirect_query(user_query = nil)
      if self.ignore_user_query?
          # Ignore the passed in user_query
          Redirection::empty_string_to_nil(self.redirect_to_query)
      else
          if user_query
              # Passed in user_query is not nil
              Redirection::empty_string_to_nil(user_query)
          else
              # Passed in user_query is nil
              Redirection::empty_string_to_nil(self.redirect_to_query)
          end
      end
  end

  def clear_cache
    if AppConfig.get(%w(redirections cache_redirects), APP_CONFIG)
      Rails.cache.delete(self.cache_tag) if AppConfig.get(%w(redirections cache_redirects_clear_on_save), APP_CONFIG)

      self.write_to_cache if AppConfig.get(%w(redirections cache_redirects_on_save), APP_CONFIG)
    end
  end
end

app/controllers/api/v1/redirections_controller.rb
class API::V1::RedirectionsController < API::APIBaseController
  load_and_authorize_resource
  before_action :set_redirection, only: [:show, :update, :destroy]

  # GET /redirections.json
  def index
    @redirections = Redirection.all
  end

  # GET /redirections/1.json
  def show
  end

  # POST /redirections.json
  def create
    @redirection = Redirection.new(redirection_params)
    @redirection.user = current_user

    respond_to do |format|
      if @redirection.save
        format.json { render :show, status: :created, location: redirection_path(@redirection) }
      else
        format.json { render json: @redirection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redirections/1.json
  def update
    respond_to do |format|
      if @redirection.update(redirection_params)
        format.json { render :show, status: :ok, location: redirection_path(@redirection) }
      else
        format.json { render json: @redirection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redirections/1.json
  def destroy
    @redirection.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_redirection
    @redirection = Redirection.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def redirection_params
    params.require(:redirection).permit(:from_url, :to_url, :from_path, :from_query, :to_path, :redirect_to_query, :redirection_type, :ignore_user_path, :ignore_user_query).merge(:audit_comment => "api_key_id=#{current_api_key.id}")
  end
end

app/controllers/redirections_controller.rb
class RedirectionsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => [:redirect]
  before_action :set_redirection, only: [:show, :edit, :update, :destroy]
  before_action :text_type, only: [:index, :show]
  before_filter :owner?, only: [:edit, :update, :destroy]

  # GET /redirections
  def index
    @redirections = Redirection.all

    respond_to do |format|
      format.html
      format.text
      format.csv { send_data @redirections.to_csv }
    end
  end

  # GET /redirections/1
  def show
  end

  # GET /redirections/new
  def new
    @redirection = Redirection.new
  end

  # GET /redirections/1/edit
  def edit
  end

  # POST /redirections
  def create
    @redirection = Redirection.new(redirection_params)
    @redirection.user = current_user

    respond_to do |format|
      if @redirection.save
        format.html { redirect_to @redirection, notice: 'Redirection was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /redirections/1
  def update
    respond_to do |format|
      if @redirection.update(redirection_params)
        format.html { redirect_to @redirection, notice: 'Redirection was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /redirections/1
  def destroy
    @redirection.destroy
    respond_to do |format|
      format.html { redirect_to redirections_url, notice: 'Redirection was successfully destroyed.' }
    end
  end

  def redirect
    cache_redirects = AppConfig.get(%w(redirections cache_redirects), APP_CONFIG)

    if cache_redirects
      @redirection = Rails.cache.fetch(Redirection.cache_tag(params), :expires_in => cache_ttl.seconds)

      unless @redirection
        @redirection = Redirection.find_by_relevance(params[:from_url], params[:path], params[:query]).first

        @redirection.write_to_cache(params[:path]) if @redirection
      end
    else
      @redirection = Redirection.find_by_relevance(params[:from_url], params[:path], params[:query]).first
    end

    if @redirection
      fresh_when(:etag => @redirection, :last_modified => @redirection.created_at.utc, :public => true) if cache_redirects

      options = {
          :path => params[:path],
          :query => params[:query]
      }

      redirect_to(@redirection.build_url(options), :status => @redirection.redirection_type_hash[:status_code])
    else
      not_found
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_redirection
    @redirection = Redirection.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def redirection_params
    params.require(:redirection).permit(:from_url, :to_url, :from_path, :from_query, :to_path, :redirect_to_query, :redirection_type, :ignore_user_path, :ignore_user_query)
  end

  def owner?
    @redirection.user == current_user || current_user.has_role?(:admin)
  end

  def text_type
    if request.format.symbol == :text
      case params[:text_type]
        when 'apache'
          @text_type = :apache
        else
          @text_type = :apache
      end
    end
  end

  def cache_ttl
    cache_ttl = AppConfig.get(%w(redirections cache_redirects_ttl), APP_CONFIG)

    cache_ttl.is_a?(Integer) ? cache_ttl.to_i : 86400
  end
end

app/helpers/api/v1/redirections_helper.rb
module API::V1::RedirectionsHelper
end

app/helpers/redirections_helper.rb
module RedirectionsHelper
  def redirection_types_collection
    redirection_types = Array.new

    types = Redirection::REDIRECTION_TYPES.select { |k,v| k != :default }

    types.each do |k,v|
      redirection_types << {
          :key => k,
          :description => "#{v[:status_code]} #{v[:description]}"
      }
    end

    redirection_types
  end

  def redirection_type_to_s(redirection_type)
    type = Redirection::REDIRECTION_TYPES[redirection_type.to_sym]

    "#{type[:status_code]} #{type[:description]}"
  end
end

app/views/redirections/_form.html.erb
<%= form_for(@redirection) do |f| %>
  <% if @redirection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@redirection.errors.count, "error") %> prohibited this redirection from being saved:</h2>

      <ul>
      <% @redirection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <h3><%= t('redirections.from_parameters') %></h3>
  <div class="field">
    <%= f.label :from_url %><br>
    <%= f.text_field :from_url %>
  </div>
  <div class="field">
    <%= f.label :from_path %><br>
    <%= f.text_field :from_path %>
  </div>
  <div class="field">
    <%= f.label :from_query %><br>
    <%= f.text_field :from_query %>
  </div>
    <p></p>
    <p></p>
  </div>
  <div>
  <h3><%= t('redirections.to_parameters') %></h3>
  <div class="field">
    <%= f.label :to_url %><br>
    <%= f.text_field :to_url %>
  </div>
  <div class="field">
    <%= f.label :to_path %><br>
    <%= f.text_field :to_path %>
  </div>
  <div class="field">
    <%= f.label :redirect_to_query %><br>
    <%= f.text_field :redirect_to_query %>
  </div>
    <p></p>
    <p></p>
  </div>
  <div>
  <h3><%= t('redirections.general_parameters') %></h3>
  <div class="field">
    <%= f.label :ignore_user_path, t('redirections.ignore_user_path') %><br>
    <%= f.check_box :ignore_user_path %>
  </div>
  <div class="field">
    <%= f.label :ignore_user_query, t('redirections.ignore_user_query') %><br>
    <%= f.check_box :ignore_user_query %>
  </div>
  <div class="field">
    <%= f.label :redirection_type, t('redirections.type') %><br />
    <%= f.select :redirection_type, options_for_select(redirection_types_collection.collect {|p| [ p[:description], p[:key] ] }, (@redirection.redirection_type.nil? ? Redirection::REDIRECTION_TYPES[:default].to_s : @redirection.redirection_type ))  %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/redirections/_redirections.html.erb
<table id='index_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('redirections.from_url') %></th>
    <th><%= t('redirections.to_url') %></th>
    <th><%= t('users.creator') %></th>
    <th><%= t('general.tables.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% redirections.each do |redirection| %>
      <tr>
        <td><%= redirection.from_url %></td>
        <td><%= redirection.to_url %></td>
        <td><%= redirection.user.full_name %></td>
        <td>
          <%= link_to t('general.show'), redirection %>
          <%= link_to t('general.edit'), edit_redirection_path(redirection) if can? :edit, Redirection %>
          <%= link_to t('general.destroy'), redirection, method: :delete, data: { confirm: t('general.are_you_sure')} if can? :destroy, Redirection %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/redirections/edit.html.erb
<h1><%= t('general.editing') % t('redirections.redirection') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Show', @redirection %> |
<%= link_to 'Back', redirections_path %>

app/views/redirections/index.html.erb
<h1><%= t('general.listing') % t('redirections.redirection') %>
  <span class='actions'>
        <% if can? :create, Redirection  %>
          <%= link_to 'New', new_redirection_path, :id => 'new_redirection_link' %>
        <% end  %>
    </span>
</h1>
<%= render 'redirections/redirections', :redirections => @redirections %>
<br />
<br />
<div>
  <%= "#{t('general.download')} #{t('redirections.configuration.configuration')}" %>: <%= link_to t('redirections.configuration.apache'), redirections_path(format: 'text', text_type: :apache), :target => '_blank' %> <%= link_to 'CSV', redirections_path(format: 'csv') %>
</div>

app/views/redirections/index.text.erb
<% @redirections.each do |redirection| %>
<%= render "redirections/web_servers/#{@text_type}", :redirection => redirection %><%= "\n" %>
<% end %>

app/views/redirections/new.html.erb
<h1><%= t('general.new') % t('redirections.redirection') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', redirections_path %>

app/views/redirections/show.html.erb
<h1><%= t('redirections.redirection') %>: <%= "#{@redirection.from_url} -> #{@redirection.to_url}" %></h1>
<div>
  <h3><%= t('redirections.from_parameters') %></h3>
  <strong><%= t('redirections.from_url') %>:</strong>
  <%= @redirection.from_url %><br />
  <strong><%= t('redirections.from_path') %>:</strong>
  <%= @redirection.from_path %><br />
  <strong><%= t('redirections.from_query') %>:</strong>
  <%= @redirection.from_query %><br />
</div>
<div>
<h3><%= t('redirections.to_parameters') %></h3>
<strong><%= t('redirections.to_url') %>:</strong>
<%= @redirection.to_url %><br />
<strong><%= t('redirections.to_path') %>:</strong>
<%= @redirection.to_path %><br />
<strong><%= t('redirections.to_query') %>:</strong>
<%= @redirection.redirect_to_query %><br />
</div>

<div>
<h3><%= t('redirections.general_parameters') %></h3>
  <strong><%= t('redirections.ignore_user_path') %>:</strong>
  <%= @redirection.ignore_user_path %><br />

  <strong><%= t('redirections.ignore_user_query') %>:</strong>
  <%= @redirection.ignore_user_query %><br />

  <strong><%= t('redirections.full_url') %>:</strong>
  <%= link_to @redirection.build_url, @redirection.build_url %><br />

  <strong><%= t('redirections.redirection_type') %>:</strong>
  <%= redirection_type_to_s(@redirection.redirection_type) %>
</div>
<br />
<br />
<div>
  <%= "#{t('general.download')} #{t('redirections.configuration.configuration')}" %>: <%= link_to t('redirections.configuration.apache'), redirection_path(@redirection, format: 'text', text_type: :apache), :target => '_blank' %>
</div>
<br />
<%= link_to 'Edit', edit_redirection_path(@redirection) %> |
<%= link_to 'Back', redirections_path %>

app/views/redirections/show.text.erb
<%= render "redirections/web_servers/#{@text_type}", :redirection => @redirection %>