config/routes.rb
Rails.application.routes.draw do
  resources :api_keys
  authenticated :user do
    root :to => 'redirections#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resource :users, only: [:show] do
    resources :api_keys
  end

  resources :redirections do
    collection do
      get :redirect
    end
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'
    resources :api, :controller => :api, only: [:index, :show]

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :redirections
    end

    match '*path', to: 'api_base#catch_404', via: :all, :format => :json
  end
end

app/models/api_key.rb
class APIKey < ActiveRecord::Base
  audited

  belongs_to :user


  validates :application_name, :presence => true

  validates_uniqueness_of :application_name, :scope => [:user_id]


  before_create :generate_key

  private
  def generate_key
    self.key = SecureRandom.hex(AppConfig.get(%w(api api_key_hex_length), APP_CONFIG))
  end
end

app/controllers/api_keys_controller.rb
class APIKeysController < ApplicationController
  load_and_authorize_resource
  before_action :set_api_key, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :user_allowed?, only: [:show, :edit, :update, :destroy]

  # GET /api_keys
  def index
    @api_keys = @user.api_keys
  end

  # GET /api_keys/1
  def show
  end

  # GET /api_keys/new
  def new
    @api_key = @user.api_keys.new
  end

  # GET /api_keys/1/edit
  def edit
  end

  # POST /api_keys
  def create
    @api_key = @user.api_keys.new(api_key_params)

    respond_to do |format|
      if @api_key.save
        format.html { redirect_to users_api_key_path(@api_key), notice: 'API key was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /api_keys/1
  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to users_api_key_path(@api_key), notice: 'API key was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /api_keys/1
  def destroy
    @api_key.destroy
    respond_to do |format|
      format.html { redirect_to users_api_keys_path, notice: 'API key was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_api_key
    @api_key = APIKey.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def api_key_params
    params.require(:api_key).permit(:key, :user_id, :application_name, :application_url, :description)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  def user_allowed?
    raise CanCan::AccessDenied.new unless (@api_key.user == current_user || current_user.has_role?(:admin))
  end
end

app/helpers/api_keys_helper.rb
module APIKeysHelper
end

app/views/api_keys/_api_key.html.erb
<tr>
  <td><%= link_to api_key.application_name, users_api_key_path(api_key) %></td>
  <td><%= api_key.application_url %></td>
  <td><%= api_key.key %></td>
  <td>
    <%= link_to t('general.edit'), edit_users_api_key_path(api_key) if can? :edit, APIKey %>
    <%= link_to t('general.destroy'), users_api_key_path(api_key), method: :delete, data: { confirm: t('general.are_you_sure')} if can? :destroy, APIKey %>
  </td>
</tr>

app/views/api_keys/_api_keys.html.erb
<table id='index_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('api_keys.application.name') %></th>
    <th><%= t('api_keys.application.url') %></th>
    <th><%= t('api_keys.key') %></th>
    <th><%= t('general.tables.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% api_keys.each do |api_key| %>
      <%= render 'api_keys/api_key', :api_key => api_key %>
  <% end %>
  </tbody>
</table>

app/views/api_keys/_form.html.erb
<%= form_for(@api_key, :url => resource_url) do |f| %>
  <% if @api_key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_key.errors.count, "error") %> prohibited this api_key from being saved:</h2>

      <ul>
      <% @api_key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :application_name %><br>
    <%= f.text_field :application_name %>
  </div>
  <div class="field">
    <%= f.label :application_url %><br>
    <%= f.text_field :application_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/api_keys/edit.html.erb
<h1><%= t('general.editing') % t('api_keys.api_key') %></h1>

<%= render 'form', :resource_url => users_api_key_path(@api_key) %>
<br />
<br />
<%= link_to 'Back', users_api_keys_path %>

app/views/api_keys/index.html.erb
<h1><%= t('general.listing') % t('api_keys.api_keys') %>
  <span class='actions'>
        <% if can? :create, APIKey  %>
          <%= link_to 'New', new_users_api_key_path, :id => 'new_api_key_link' %>
        <% end  %>
    </span>
</h1>
<%= render 'api_keys', :api_keys => @api_keys %>

app/views/api_keys/new.html.erb
<h1><%= t('general.new') % t('api_keys.api_key') %></h1>

<%= render 'form', :resource_url => users_api_keys_path %>
<br />
<br />
<%= link_to 'Back', users_api_keys_path %>

app/views/api_keys/show.html.erb
<h1><%= @api_key.application_name %></h1>

<p>
  <strong>Key:</strong>
  <%= @api_key.key %>
</p>
<p>
  <strong>Application url:</strong>
  <%= @api_key.application_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @api_key.description %>
</p>
<br />
<br />
<%= link_to t('general.back'), users_api_keys_path %>
<% if can?(:edit, APIKey) %>
    | <%= link_to 'Edit', edit_users_api_key_path(@api_key) %>
<% end %>